server:
  port: 8081

spring:
  application:
    name: auth-server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mddb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true

movie-delivery:
  security:
    secret: H+KbPeShVmYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B